---
title: "Homework 3 - Report"
author: "Mivelaz, Allan and van Kampen, Adrian"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

<!-- To obtain the maximum number of points, use whenever possible: -->

<!-- * the pipeline symbol %>%, -->
<!-- * `dplyr` verbs (see below), -->
<!-- * `kable` to print tables, -->
<!-- * `ggplot` to produce the figures. -->

<!-- Also:  -->

<!-- * Pay attention to the general aesthetics of your report (i.e., formatting of  -->
<!-- the tables, sizing of the figures, etc.).  -->
<!-- * Use inline code to display single numbers, and `echo = FALSE` for code chunks when you display  -->
<!-- a table of produce a figure (i.e., we don't want to see code unless it is necessary). -->
<!-- * Comment your code to explain what you are doing. -->

```{r child = '../static/dsfba_homework3/reports/dhw3_ex1.Rmd'}
```

```{r child = '../static/dsfba_homework3/reports/hw3_ex2.Rmd'}
```

```{r child = '../static/dsfba_homework3/reports/hw3_ex3.Rmd'}
```

```{r child = '../static/dsfba_homework3/reports/hw3_ex4.Rmd'}
```
